apiVersion: apps/v1
kind: Deployment
metadata:
  name: airasia-backend
spec:
  selector:
    matchLabels:
      app: airasia-backend
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: airasia-backend
    spec:
      containers:
        - name: main
          image: asia.gcr.io/k8s-session/airasia-backend:0.0.1
          imagePullPolicy: Always # if local, utilize Never
          ports:
            - containerPort: 8080
